apiVersion: v2
name: drs-filer
description: A Helm chart for deploying a DRS (Data Repository Service) filer on Kubernetes, facilitating efficient data storage and retrieval.
type: application
version: 2.0.0
appVersion: 2.0.0
