apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rabbitmq.appName }}
  labels:
    app: {{ .Values.rabbitmq.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.appName }}
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        command:
          - /bin/sh
          - -c
          - |
            chmod g-rw /var/lib/rabbitmq/.erlang.cookie;    # If rabbitMQ deployment is restarted (e.g. cluster failure) cookie has incorrect permissions
            /opt/rabbitmq/sbin/rabbitmq-server              # Solved by chmod before calling rabbitmq (https://github.com/elixir-cloud-aai/cwl-WES/issues/232)
        volumeMounts:
        - mountPath: /var/lib/rabbitmq
          name: rabbitmq-volume
      volumes:
      - name: rabbitmq-volume
        persistentVolumeClaim:
          claimName: {{ .Values.rabbitmq.appName }}-volume
{{- if .Values.securityContext }}
      securityContext:
{{- toYaml .Values.securityContext | nindent 8 -}}
{{- end }}

