apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.appName }}
  labels:
    app: {{ .Values.mongodb.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.mongodb.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.appName }}
    spec:
      {{ if eq .Values.clusterType "kubernetes" }}
      initContainers:
        - name: volume-permissions
          image: busybox
          imagePullPolicy: {{ .Values.mongodb.pullPolicy | quote }}
          command: ["chown", "-R", "{{ .Values.mongodb.securityContext.runAsUser }}:{{ .Values.mongodb.securityContext.fsGroup }}", "{{ .Values.mongodb.mountPath }}"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: mongodb-data
              mountPath: {{ .Values.mongodb.mountPath }}
      {{ end }}
      containers:
        - env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                key: databaseRootUsername
                name: {{ .Values.mongodb.appName }}
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: databaseRootPassword
                name: {{ .Values.mongodb.appName }}
          - name: MONGO_INITDB_DATABASE
            valueFrom:
              secretKeyRef:
                key: databaseName
                name: {{ .Values.mongodb.appName }}
          - name: MONGO_APP_USERNAME
            valueFrom:
              secretKeyRef:
                key: databaseUser
                name: {{ .Values.mongodb.appName }}
          - name: MONGO_APP_PASSWORD
            valueFrom:
              secretKeyRef:
                key: databasePassword
                name: {{ .Values.mongodb.appName }}
          image: {{ .Values.mongodb.image }}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          name: mongodb
          ports:
            - containerPort: 27017
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - '-i'
                - '-c'
                - >-
                  mongosh --host 127.0.0.1:27017 -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin $MONGO_INITDB_DATABASE --eval="quit()" 
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 50
          resources: {{- toYaml .Values.mongodb.resources | nindent 12 }}
          {{ if eq .Values.clusterType "kubernetes" }}
          securityContext:
            runAsNonRoot: {{ .Values.mongodb.securityContext.runAsNonRoot }}
            runAsUser: {{ .Values.mongodb.securityContext.runAsUser }}
          {{ end }}
          volumeMounts:
            - mountPath: {{ .Values.mongodb.mountPath }}
              name: mongodb-data
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-script.js
              subPath: init-script.js
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: {{ .Values.mongodb.appName }}-volume
        - name: init-script
          configMap:
            name: mongo-init-script
