apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.mongodb.appName }}
data:
  {{- range $key, $val := .Values.mongodb.secret }}
    "{{ $key }}": "{{ tpl $val $ | b64enc }}"
  {{- end }}
