apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celeryWorker.appName }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.celeryWorker.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.celeryWorker.appName }}
    spec:
      initContainers:
      - name: vol-init
        image: busybox
        command: [ 'mkdir' ]
        args: [ '-p', '/data/db', '/data/output', '/data/tmp' ]
        volumeMounts:
        - mountPath: /data
          name: wes-volume
      containers:
      - name: celery-worker
        image: {{ .Values.celeryWorker.image }}
        imagePullPolicy: Always
        workingDir: '/app/cwl_wes'
        command: [ 'celery' ]
        args: [ 'worker', '-A', 'celery_worker', '-E', '--loglevel=info', '-c', '1', '-Q', 'celery' ]
        env:
        - name: MONGO_HOST
          value: {{ .Values.mongodb.appName }}
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_USERNAME
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{ .Values.mongodb.appName }}
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{ .Values.mongodb.appName }}
        - name: MONGO_DBNAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{ .Values.mongodb.appName }}
        - name: RABBIT_HOST
          value: {{ .Values.rabbitmq.appName }}
        - name: RABBIT_PORT
          value: "5672"
        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "8Gi"
            cpu: "1"
        volumeMounts:
        - mountPath: /data
          name: wes-volume
        - mountPath: /app/cwl_wes/config/app_config.yaml
          subPath: app_config.yaml
          name: wes-config
        - mountPath: /.netrc 
          subPath: .netrc
          name: wes-netrc-secret
      volumes:
      - name: wes-volume
        persistentVolumeClaim:
          claimName: {{ .Values.wes.appName }}-volume
      - name: wes-config
        configMap:
          defaultMode: 420
          name: {{ .Values.wes.appName }}-config
      - name: wes-netrc-secret
        secret:
          secretName: netrc
          items:
          - key: netrc
            path: .netrc

