apiVersion: v1
kind: Secret
metadata:
  name: netrc
type: Opaque
stringData:
  netrc: |-
    machine {{ .Values.wes.netrcMachine }}
    login {{ .Values.wes.netrcLogin }}
    password {{ .Values.wes.netrcPassword }}