apiVersion: v1
kind: Secret
metadata:
  name: netrc
type: Opaque
stringData:
  netrc: |-
    {{- range .Values.wes.netrc }}
    machine {{ .Machine }}
    login {{ .Login }}
    password {{ .Password }}
    {{ end }}
