{{ if eq .Values.clusterType "kubernetes" }}
{{ if .Values.ingress.letsencryptSystem }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wes-ingress-kubernetes {{ if .Values.ingress.tls_letsencrypt }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.tls_letsencrypt.annotations.ingressclass }}
    kubernetes.io/tls-acme: {{ .Values.ingress.tls_letsencrypt.annotations.tlsacme }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls_letsencrypt.annotations.clusterissuer }}
<<<<<<< HEAD
    nginx.ingress.kubernetes.io/app-root: "/ga4gh/wes/v1/ui/"
=======
>>>>>>> refs/remotes/origin/dev
  {{ end }}
spec: {{ if .Values.tlsSecret }}
  tls:
    - hosts:
        - {{ .Values.applicationDomain }}
      secretName: {{ .Values.tlsSecret }} {{ end }}
  rules:
    - host: {{ .Values.applicationDomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Values.wes.appName }}
              servicePort: 8080
{{ else }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.wes.appName }}
  labels:
    app: {{ .Values.wes.appName }}
spec:
  rules:
  - host: {{ .Values.wes.appName }}.{{ .Values.applicationDomain }}
    http:
      paths:
      - path: "/.well-known"
        backend:
          serviceName: {{ .Values.wes.appName }}-certbot
          servicePort: 8080
      - path: "/ga4gh/wes/v1"
        backend:
          serviceName: {{ .Values.wes.appName }}
          servicePort: 8080
  {{ if ne .Values.tlsSecret "" }}
  tls:
  - secretName: {{ .Values.tlsSecret }}
    hosts:
    - {{ .Values.wes.appName }}.{{ .Values.applicationDomain }}
  {{ end }}
{{ end }}
{{ end }}
