# Default values for protes_helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

applicationDomain: c03.k8s-popup.csc.fi
clusterType: openshift
tlsSecret: mytls-secret

autocert:
  # autocert.createJob -- Actually create autocert cronjob
  createJob: "true" 
  # autocert.schedule -- How often to refresh certs
  schedule: "0 0 1 */2 *" 
  # autocert.testCert -- use letsencryptit staging for testing not to exceed cert quota
  testCert: "true" 
  image: elixircloud/autocert:devel
  # autocert.apiServer -- where to reach k8s apiserver
  apiServer: kubernetes.default.svc:443
  # autocert.email -- which email to inject to the certificate
  email: cert.author@cert.author.host.org

wes:
  # wes.appName -- name of the application in k8s cluster
  appName: wes
  # wes.image -- which image if WES to use
  image: weselixir/elixir-wes-app:rc1
  # wes.netrcMachine -- SFTP machine adddress
  netrcMachine: defaultmachine
  netrcLogin: defaultnetrclogin
  netrcPassword: defaultnetrcpassword
  # wes.volumeSize -- Size of the PVC volume for WES
  volumeSize: 1Gi

celeryWorker:
  appName: celery-worker-wes
  image: weselixir/elixir-wes-app:rc1

mongodb:
  appName: mongodb
  databaseAdminPassword: adminpasswd
  databaseName: wes-elixir-db
  databasePassword: protes-db-passwd
  databaseUser: protes-user
  # mongodb.volumeSize -- Size for mongodb database
  volumeSize: 1Gi
  image: centos/mongodb-36-centos7

rabbitmq:
  appName: rabbitmq
  # rabbitmq.volumeSize -- Size for mongodb database
  volumeSize: 1Gi
  image: rabbitmq:3-management

