{{- if eq .Values.clusterType "openshift" }}
apiVersion: route.openshift.io/v1
kind: Route
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
{{ end }}
metadata:
  labels:
    app: {{ .Values.flower.appName }}
  name: {{ .Values.flower.appName }}
spec:
{{- if eq .Values.clusterType "openshift" }}
  host: {{ .Values.wes.appName }}-{{ .Values.flower.appName }}.{{ .Values.applicationDomain }}
  port:
    targetPort: 5555
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ .Values.flower.appName }}
    weight: 100
  wildcardPolicy: None
status:
  ingress: []
{{- else }}
  tls:
  - hosts:
      - {{ .Values.wes.appName }}-{{ .Values.flower.appName }}.{{ .Values.applicationDomain }}
  rules:
  - host: {{ .Values.wes.appName }}-{{ .Values.flower.appName }}.{{ .Values.applicationDomain }}
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.flower.appName }}
            port: 
              number: 5555
{{ end }}
