name: Docker Image CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  DOCKER_REPO_NAME: elixircloud/cwl-wes

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_NAME: elixircloud/cwl-wes
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${DOCKER_REPO_NAME}:$(date +%Y%m%d) --tag ${DOCKER_REPO_NAME}:latest
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set today env variable
      run: |
        echo "today=$(date +%Y%m%d)" >> $GITHUB_ENV
    - name: Build and push
      uses: docker/build-push-action@v2
      if: github.ref == 'refs/heads/dev'
      with:
          context: .
          push: true
          tags: |
              ${{ env.DOCKER_REPO_NAME }}:${{ env.today }}
              ${{ env.DOCKER_REPO_NAME }}:latest
